# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_class',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('revenue', 'Income/Revenue'), ('expense', 'Expense'), ('equity', 'Equity/Capital')], default=1, max_length=64, verbose_name='Account Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.TextField(help_text="this field is only used for displaying information during\n            debugging.  It's best to use a OneToOne relationship with another\n            table to hold all the information you actually need.", verbose_name='name memo'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('bookset', 'name')]),
        ),
    ]
